# Generated by Django 4.2.21 on 2025-05-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking',
            new_name='Reservation',
        ),
    ]
