# Generated by Django 4.2.21 on 2025-05-22 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_booking_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_code',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
