# Generated by Django 4.2.21 on 2025-05-22 08:35

from django.db import migrations
import uuid


def gen_booking_code(apps, schema_editor):
    Reservation = apps.get_model("booking", "Reservation")
    for reservation in Reservation.objects.all():
        reservation.booking_code = uuid.uuid4()
        reservation.save(update_fields=["booking_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_reservation_booking_code'),
    ]

    operations = [
        migrations.RunPython(gen_booking_code, reverse_code=migrations.RunPython.noop),
    ]
