# Generated by Django 4.2.21 on 2025-05-22 08:35

from django.db import migrations, models
import uuid 

class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_populate_booking_code'),
    ]

    operations = [
         migrations.AlterField(
            model_name='reservation',
            name='booking_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
         ),
    ]
